### PR TITLE
Metadata fixes - required

### PR DESCRIPTION
**Pull request by cjgronlund**
Metadata fixes only

### CODE REVIEW

**Comment by cjgronlund** [comment]
#sign-off
Ready for merge. This PR includes metadata updates. 
I also fixed a few broken links. I'm not able to resolve the issue with broken links to .py files.

**Comment by cjgronlund** [comment]
@thiagocrepaldi @mx-iao 
These changes aren't live yet, because you haven't merged master to a production branch. I contacted publishing support, and here is what they said you need to do (I don't have perms to do this):

Your content change is made on master branch. So, you can't see that on PROD page. However, you can find your change here: https://review.docs.microsoft.com/en-us/cognitive-toolkit/?branch=master
If you want to show the change to PROD page, please merge your content from master to live branch which is source content of PROD published page.

**Comment by thiagocrepaldi** [comment]
@cjgronlund Done

**Comment by cjgronlund** [comment]
@thiagocrepaldi Awesome! Thank you. :>)

**Pull request merged**
